bms/models.py
from bms import db,loginmanager
from flask_login import UserMixin

@loginmanager.user_loader
def load_user(user_id):
  return User.query.get(int(user_id))

class User(db.Model,UserMixin):
  id = db.Column(db.Integer,primary_key = True)
  name = db.Column(db.String(100),nullable = False)
  password = db.Column(db.String(60),nullable = False)
  email = db.Column(db.String(100),nullable = False,unique=True)
  usertype = db.Column(db.Boolean,nullable = False)

  def __repr__(self):
    return f"User('{self.name}','{self.password}','{self.email}','{self.usertype}')"


    

bms/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField
from wtforms.validators import DataRequired,Length,EqualTo,ValidationError
from bms.models import User

class LoginForm(FlaskForm):
  email = StringField('Email',validators = [DataRequired()])
  password = PasswordField('Password',validators = [DataRequired(),Length(min = 8)])
  submit = SubmitField('Login')

class RegisterForm(FlaskForm):
  username = StringField('Username',validators = [DataRequired(),Length(min=5)])
  email = StringField('Email',validators = [DataRequired()])
  password = PasswordField('Password',validators = [DataRequired(),Length(min = 8)])
  confirm_password = PasswordField('Confirm Password',validators = [DataRequired(),EqualTo('password')])
  submit = SubmitField('Register')

  def validate_username(self,username):
    user=User.query.filter_by(name=username.data).first()
    if user:
      raise ValidationError('This username already exists.Try another!')

  def validate_email(self,email):
    user=User.query.filter_by(email=email.data).first()
    if user:
      raise ValidationError('This email already exists.Try another!')

bms/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
import os

app = Flask(__name__)
db = SQLAlchemy(app)
bcrypt = Bcrypt(app)
loginmanager = LoginManager(app)
app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')
app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('SQLALCHEMY_DATABASE_URI')
loginmanager.login_view = 'main.login'
loginmanager.login_message = 'You need to login to access this page'
loginmanager.login_message_category = 'info'


from bms.owners.routes import owners
from bms.parents.routes import parents
from bms.main.routes import main
app.register_blueprint(owners)
app.register_blueprint(parents)
app.register_blueprint(main)

bms/main/routes.py
from flask import Blueprint,render_template,redirect,flash,url_for,request
from bms.main.forms import LoginForm,RegisterForm
from bms.models import User
from bms import db,bcrypt
from flask_login import login_user,logout_user

main = Blueprint('main',__name__)

@main.route("/index")
def auth_home():
  return render_template('auth_home.html',title='Home')


@main.route("/")
@main.route("/home")
def home():
  return render_template('index.html',title='Home')

@main.route("/about")
def about():
  return render_template('about.html',title='About')

@main.route("/contact")
def contact():
  return render_template('contact.html',title='Contact')

@main.route("/school-list")
def feedback():
  return render_template('school_list.html',title='School List')

@main.route("/login",methods=['GET','POST'])
def login():
  # if current_user.is_authenticated:
  #   flash(f'Already authenticated','danger')
  #   return redirect(url_for('main.home'))
  forms = LoginForm()
  if forms.validate_on_submit():
    user = User.query.filter_by(email=forms.email.data).first()
    if user and bcrypt.check_password_hash(user.password,forms.password.data):
      login_user(user)
      flash(f'Login success (db)!','success')
      req_page = request.args.get('next')
      if user.usertype == 1:
        return redirect(req_page) if req_page else redirect(url_for('owners.owner_dash'))
      return redirect(req_page) if req_page else redirect(url_for('parents.parent_dash'))
    else:
      flash(f'Incorrect username or password!','danger')
  return render_template('login.html',title='Login',forms = forms)

@main.route("/register",methods=['GET','POST'])
def register():
  # if current_user.is_authenticated:
  #   flash(f'Already authenticated','danger')
  #   return redirect(url_for('main.home'))
  forms = RegisterForm()
  if forms.validate_on_submit():  
    if request.form.get('check_type') == '1':
      user_type_data = 1
    else:
      user_type_data = 0
    hash_password = bcrypt.generate_password_hash(forms.password.data).decode('utf-8')
    user = User(name=forms.username.data,password=hash_password,email=forms.email.data,usertype=user_type_data)
    db.session.add(user)
    db.session.commit()
    flash(f'Registeration success.You can login now!','success')
    return redirect(url_for('main.login'))  
    
  return render_template('register.html',title = 'Register',forms = forms)



@main.route("/logout")
def logout():
  logout_user()
  flash(f'Logout success','success')
  return redirect(url_for('main.home'))

bms/owners/routes.py
from flask import Blueprint,render_template,flash,url_for,redirect
from flask_login import current_user,login_required

owners = Blueprint('owners',__name__)

@owners.route("/owner")
@login_required
def owner_dash():
  if current_user.usertype == 0:
    flash(f'You can\'t access this page','danger')
    return redirect(url_for('parents.parent_dash'))
  return render_template('owner_dash.html',title = 'Owner Dashboard')

@owners.route("/owner/profile")
@login_required
def owner_profile():
  if current_user.usertype == 0:
    flash(f'You can\'t access this page','danger')
    return redirect(url_for('parents.parent_dash'))
  return render_template('owner_profile.html',title = 'Profile')

@owners.route("/owner/car-list")
@login_required
def car_list():
  if current_user.usertype == 0:
    flash(f'You can\'t access this page','danger')
    return redirect(url_for('parents.parent_dash'))
  return render_template('car_list.html',title = 'Car List')

@owners.route("/owner/student-list")
@login_required
def student_list():
  if current_user.usertype == 0:
    flash(f'You can\'t access this page','danger')
    return redirect(url_for('parents.parent_dash'))
  return render_template('student_list.html',title = 'Student List')

@owners.route("/owner/salary-list")
@login_required
def salary_list():
  if current_user.usertype == 0:
    flash(f'You can\'t access this page','danger')
    return redirect(url_for('parents.parent_dash'))
  return render_template('salary_list.html',title = 'Salary List')

@owners.route("/owner/school-list")
@login_required
def school_list():
  if current_user.usertype == 0:
    flash(f'You can\'t access this page','danger')
    return redirect(url_for('parents.parent_dash'))
  return render_template('school_list.html',title = 'School List')



@owners.route("/owner/car-info")
@login_required
def car_info():
  if current_user.usertype == 0:
    flash(f'You can\'t access this page','danger')
    return redirect(url_for('parents.parent_dash'))
  return render_template('car_info.html',title = 'Car Info')

@owners.route("/owner/add")
@login_required
def add_car():
  if current_user.usertype == 0:
    flash(f'You can\'t access this page','danger')
    return redirect(url_for('parents.parent_dash'))
  return render_template('add_car.html',title = 'New Car')

bms/parents/routes.py
from flask import Blueprint,render_template,flash,redirect,url_for
from flask_login import current_user,login_required

parents = Blueprint('parents',__name__)

@parents.route("/parent")
@login_required
def parent_dash():
  if current_user.usertype == 1:
    flash(f'You can\'t access this page','danger')
    return redirect(url_for('owners.owner_dash'))
  return render_template('parent_dash.html',title = 'Parent Dashboard')

@parents.route("/parent/profile")
@login_required
def parent_profile():
  if current_user.usertype == 1:
    flash(f'You can\'t access this page','danger')
    return redirect(url_for('owners.owner_dash'))
  return render_template('parent_profile.html',title = 'Profile')

bms/templates/car_info.html
{% extends 'dashboard_layout.html' %}
{% block content %}
  <div class="row">
    <div class="col-12 col-md-12 col-lg-5 mb-4">
        <div class="showcarinfobox">
          <p class="text-left ml-3 sec-title-font">Car Information</p>                              
          <div class="car-content">
            <table>
              <tr>
                <td> 
                  <i class="fab fa-modx">&nbsp;&nbsp;&nbsp;</i>Model&nbsp;&nbsp;
                </td>
                <td>
                  C-9
                </td>
              </tr>  
              <tr>
                <td> 
                  <i class="fas fa-border-style">&nbsp;&nbsp;&nbsp;</i>Car Type&nbsp;&nbsp;
                </td>
                <td>
                  Toyota
                </td>
              </tr>
              <tr>
                <td>                   
                  <i class="far fa-address-card">&nbsp;&nbsp;&nbsp;</i>Car Number&nbsp;&nbsp;
                </td>
                <td>
                  CN-99332567890
                </td>
              </tr>
              <tr>
                <td> 
                  <i class="fas fa-users">&nbsp;&nbsp;&nbsp;</i>Number of passengers&nbsp;&nbsp;
                </td>
                <td>
                  12
                </td>
              </tr>
              <tr>
                <td> 
                  <i class="fas fa-palette">&nbsp;&nbsp;&nbsp;</i>Color&nbsp;&nbsp;
                </td>
                <td>
                Grey
                </td>
              </tr>
            </table>
          </div>                 
          <div class="car-back-button">      
            <a href="{{ url_for('owners.car_list') }}">
              <button class="car-back">Back</button>
            </a>
          </div>          
        </div>
    </div>
    <div class="col-12 col-md-12 col-lg-7 mb-4">          
      <div class="showmoreinfo-car">
        <p class="text-left ml-3 sec-title-font">More</p>
      </div>                          
    </div>
  </div>    
{% endblock content %}
{% block script %}
<script>
  $jq=jQuery.noConflict();
  $jq(document).ready(function(e) {
  });
</script>
{% endblock script %}

bms/templates/car_list.html
{% extends 'dashboard_layout.html' %}
{% block li %}
<li class="nav-item">
  <a class="nav-link mr-2" style="color:black;" onclick="on()">
    <span class="icon icon-plus"></span>
    Add
  </a>
</li> 
<!-- <li class="nav-item">
  <a id="edit-button" class="nav-link mr-2" style="color:black;" onclick="edit()">
    <span class="icon icon-note"></span>
    Edit
  </a>
</li> 
<li class="nav-item">
  <a id="remove-button" class="nav-link mr-2" style="color:black;" onclick="del()">
    <span class="icon icon-minus"></span>
    Remove
  </a>
</li>  -->
{% endblock li %}
{% block breadcrumb %}
<nav aria-label="breadcrumb" style="margin-top:-39px;">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ url_for('owners.owner_dash') }}" style="font-size: 20px;color: black;">Dashboard</a></li>
    <li class="breadcrumb-item active" aria-current="page" style="font-size: 20px;">Car List</li>
  </ol>
</nav>  
{% endblock breadcrumb %}
{% block content %}  
  <div id="hidecar-overlay">
      <!-- hidden box for adding new car -->
      <div class="hideprofiletable overlay-car-edit" style="display:block;">
			    <table>
            <tr style="background:transparent;">
              <td>
                <select class="custom-select" style="margin-left:-10px;">
                  <option>School-1</option>
                  <option>School-1</option>
                  <option>School-1</option>
                  <option>School-1</option>
                  <option>School-1</option>
                  <option>School-1</option>
                  <option>School-1</option>
                  <option>School-1</option>                  
                </select>
              </td>        
              <td>
                <select class="custom-select">
                  <option value="1">Morning</option>
                  <option value="2">Afternoon</option>
                </select>
              </td>
            </tr>                     
            <tr>
              <td> 
              <i class="fab fa-modx">&nbsp;&nbsp;&nbsp;</i>Model&nbsp;&nbsp;
              </td>              
              <td>
              <input type="text" name="name" placeholder="eg. Honda Fit" class="inputprofile">
              </td>
            </tr>
            <tr>
              <td> 
              <i class="fas fa-border-style">&nbsp;&nbsp;&nbsp;</i>Type&nbsp;&nbsp;
              </td>              
              <td>
              <input type="text" name="type" placeholder="eg. luxury" class="inputprofile">
            </td>
            </tr>

            <tr>
              <td> 
              <i class="far fa-address-card">&nbsp;&nbsp;&nbsp;</i>Car No.
              <b style="color:red"> *</b>&nbsp;&nbsp;
              </td>              
              <td>
              <input type="text" name="carno" placeholder="eg. AA-1111" class="inputprofile">
              </td>
            </tr>
            <tr>
              <td> 
              <i class="fas fa-users">&nbsp;&nbsp;&nbsp;</i>No. of Passengers&nbsp;&nbsp;
              </td>              
              <td>
              <input type="text" name="nopassenger" placeholder="eg. 12" class="inputprofile">
              </td>
            </tr>          
            <tr>
              <td> 
              <i class="fas fa-palette">&nbsp;&nbsp;&nbsp;</i>Color&nbsp;&nbsp;
              </td>              
              <td>
              <input type="text" name="color" placeholder="eg. Black" class="inputprofile">
              </td>
            </tr>                                                
          </table>    
          <div class="photo p-2 border">
            <input type="file" class="photo-upload">  
          </div>    
          <button class="profileback-car" onclick="off()">Back</button>
          <button class="profilesubmit-car">Save</button>
      </div>
      <!-- hidden box for adding new car -->
  </div>
<!-- list for all register-car -->
<div class="show-all-car mt-4">
  <div class="row">
    <div class="col-sm-12 col-lg-4 col-md-6">            
      
      <div class="car-info-box">        
        <div class="car-img-left-box">
          <img src="{{ url_for('static',filename='images/s3.jpg') }}" alt="Feature Item" class="img-responsive">
        </div>
        <div class="content-right-box">                    
          <div class="car-over-box">
            <p class=""><i class="fas fa-bus-alt pr-3 pl-3"></i>Toyota</p> 
            <p class="pt-3 pb-3"></p>  
            <p class=""><i class="fas fa-user pr-3 pl-3"></i>Aung Naing Khant hkdfjs sdfjsdfljs</p>
          </div>                    
          <a href="{{ url_for('owners.car_info')}}" class="p-2 bg-dark text-white" style="float:right;">More<i class="fas fa-chevron-circle-right pl-3"></i></a>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-lg-4 col-md-6">            
      
      <div class="car-info-box">        
        <div class="car-img-left-box">
          <img src="{{ url_for('static',filename='images/s3.jpg') }}" alt="Feature Item" class="img-responsive">
        </div>
        <div class="content-right-box">                    
          <div class="car-over-box">
            <p class=""><i class="fas fa-bus-alt pr-3 pl-3"></i>Toyota</p> 
            <p class="pt-3 pb-3"></p>  
            <p class=""><i class="fas fa-user pr-3 pl-3"></i>Aung Naing Khant hkdfjs sdfjsdfljs</p>
          </div>                    
          <a href="{{ url_for('owners.car_info')}}" class="p-2 bg-dark text-white" style="float:right;">More<i class="fas fa-chevron-circle-right pl-3"></i></a>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-lg-4 col-md-6">            
      
      <div class="car-info-box">        
        <div class="car-img-left-box">
          <img src="{{ url_for('static',filename='images/s3.jpg') }}" alt="Feature Item" class="img-responsive">
        </div>
        <div class="content-right-box">                    
          <div class="car-over-box">
            <p class=""><i class="fas fa-bus-alt pr-3 pl-3"></i>Toyota</p> 
            <p class="pt-3 pb-3"></p>  
            <p class=""><i class="fas fa-user pr-3 pl-3"></i>Aung Naing Khant hkdfjs sdfjsdfljs</p>
          </div>                    
          <a href="{{ url_for('owners.car_info')}}" class="p-2 bg-dark text-white" style="float:right;">More<i class="fas fa-chevron-circle-right pl-3"></i></a>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-lg-4 col-md-6">            
      
      <div class="car-info-box">        
        <div class="car-img-left-box">
          <img src="{{ url_for('static',filename='images/s3.jpg') }}" alt="Feature Item" class="img-responsive">
        </div>
        <div class="content-right-box">                    
          <div class="car-over-box">
            <p class=""><i class="fas fa-bus-alt pr-3 pl-3"></i>Toyota</p> 
            <p class="pt-3 pb-3"></p>  
            <p class=""><i class="fas fa-user pr-3 pl-3"></i>Aung Naing Khant hkdfjs sdfjsdfljs</p>
          </div>                    
          <a href="{{ url_for('owners.car_info')}}" class="p-2 bg-dark text-white" style="float:right;">More<i class="fas fa-chevron-circle-right pl-3"></i></a>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-lg-4 col-md-6">            
      
      <div class="car-info-box">        
        <div class="car-img-left-box">
          <img src="{{ url_for('static',filename='images/s3.jpg') }}" alt="Feature Item" class="img-responsive">
        </div>
        <div class="content-right-box">                    
          <div class="car-over-box">
            <p class=""><i class="fas fa-bus-alt pr-3 pl-3"></i>Toyota</p> 
            <p class="pt-3 pb-3"></p>  
            <p class=""><i class="fas fa-user pr-3 pl-3"></i>Aung Naing Khant hkdfjs sdfjsdfljs</p>
          </div>                    
          <a href="{{ url_for('owners.car_info')}}" class="p-2 bg-dark text-white" style="float:right;">More<i class="fas fa-chevron-circle-right pl-3"></i></a>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-lg-4 col-md-6">            
      
      <div class="car-info-box">        
        <div class="car-img-left-box">
          <img src="{{ url_for('static',filename='images/s3.jpg') }}" alt="Feature Item" class="img-responsive">
        </div>
        <div class="content-right-box">                    
          <div class="car-over-box">
            <p class=""><i class="fas fa-bus-alt pr-3 pl-3"></i>Toyota</p> 
            <p class="pt-3 pb-3"></p>  
            <p class=""><i class="fas fa-user pr-3 pl-3"></i>Aung Naing Khant hkdfjs sdfjsdfljs</p>
          </div>                    
          <a href="{{ url_for('owners.car_info')}}" class="p-2 bg-dark text-white" style="float:right;">More<i class="fas fa-chevron-circle-right pl-3"></i></a>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-lg-4 col-md-6">            
      
      <div class="car-info-box">        
        <div class="car-img-left-box">
          <img src="{{ url_for('static',filename='images/s3.jpg') }}" alt="Feature Item" class="img-responsive">
        </div>
        <div class="content-right-box">                    
          <div class="car-over-box">
            <p class=""><i class="fas fa-bus-alt pr-3 pl-3"></i>Toyota</p> 
            <p class="pt-3 pb-3"></p>  
            <p class=""><i class="fas fa-user pr-3 pl-3"></i>Aung Naing Khant hkdfjs sdfjsdfljs</p>
          </div>                    
          <a href="{{ url_for('owners.car_info')}}" class="p-2 bg-dark text-white" style="float:right;">More<i class="fas fa-chevron-circle-right pl-3"></i></a>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-lg-4 col-md-6">            
      
      <div class="car-info-box">        
        <div class="car-img-left-box">
          <img src="{{ url_for('static',filename='images/s3.jpg') }}" alt="Feature Item" class="img-responsive">
        </div>
        <div class="content-right-box">                    
          <div class="car-over-box">
            <p class=""><i class="fas fa-bus-alt pr-3 pl-3"></i>Toyota</p> 
            <p class="pt-3 pb-3"></p>  
            <p class=""><i class="fas fa-user pr-3 pl-3"></i>Aung Naing Khant hkdfjs sdfjsdfljs</p>
          </div>                    
          <a href="{{ url_for('owners.car_info')}}" class="p-2 bg-dark text-white" style="float:right;">More<i class="fas fa-chevron-circle-right pl-3"></i></a>
        </div>
      </div>
    </div>
    
  </div>
</div>
<!-- list for all register-car -->
{% endblock content%}


{% block script %}
<script>
  function on() {
  document.getElementById("hidecar-overlay").style.display = "block";
  document.getElementsByTagName("body")[0].style.overflowY = 'hidden';
}

function off() {
  document.getElementById("hidecar-overlay").style.display = "none";
  document.getElementsByTagName("body")[0].style.overflowY = 'auto';
}


function del(){
  var visible = document.getElementsByClassName("event-button-delete").style.display;
  if(visible != "block"){
    document.getElementsByClassName("event-button-delete").style.display = "block"; 
    document.getElementById("remove-button").innerHTML = "Undo"; 
  }
  else{
    document.getElementsByClassName("event-button-delete").style.display = "none";  
    document.getElementById("remove-button").innerHTML = "<span class=\"icon icon-minus\"></span>Remove"; 
  }  
}

function edit(){
  var visible = document.getElementsByClassName("event-button-edit").style.display;
  if(visible != "block"){
    document.getElementsByClassName("event-button-edit").style.display = "block"; 
    document.getElementById("edit-button").innerHTML = "Undo"; 
  }
  else{
    document.getElementsByClassName("event-button-edit").style.display = "none";  
    document.getElementById("edit-button").innerHTML = "<span class=\"icon icon-note\"></span>Edit"; 
  }  
}

</script>
{% endblock script %}

bms/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap-switch-button@1.1.0/css/bootstrap-switch-button.min.css" rel="stylesheet">
    <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css">
    <link rel="stylesheet" href="{{ url_for('static',filename='owl.carousel.min.css') }}">
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
    
    <!-- font -->
    <script src="https://use.fontawesome.com/2092b8842d.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Faster+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display+SC&display=swap" rel="stylesheet"> 
    <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet"> 
    <!-- font -->
    <link rel="stylesheet" href="{{url_for('static',filename='main.css')}}">
    {% if title %}
    <title>BMS - {{ title }}</title>
    {% else %}
    <title>BMS</title>
    {% endif%}
  </head>
  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom fixed-top mb-5">
        <a class="logo-font navbar-brand mr-5" href="#">
        <img src="{{ url_for('static',filename='logo/bus2.png')}}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">&nbsp;&nbsp;&nbsp;
        BMS</a>        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="hov-ef nav-link mr-3" href="{{ url_for('main.home') }}">Home</a>
            <a class="hov-ef nav-link mr-3" href="{{ url_for('main.about') }}">About</a>           
            <a class="hov-ef nav-link" href="{{ url_for('main.contact') }}">Contact</a>
          </div>
          <div class="navbar-nav ml-auto">
              <a class="hov-ef nav-link mr-3" href="{{ url_for('main.login') }}">Login</a>
              <a class="hov-ef nav-link mr-3" href="{{ url_for('main.register') }}">Register</a>        
          </div>
        </div>
      </nav>

      <div class="content">
        {% with messages = get_flashed_messages(with_categories = true) %}
          {% if messages %}
            {% for category,message in messages %}
              <div class="container alert alert-{{ category }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}        
      </div>
      {% block content %}
      {% endblock content%}   
      {% block footer %}   
      {% endblock footer %}
    </div>    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="{{ url_for('static',filename='owl.carousel.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap-switch-button@1.1.0/dist/bootstrap-switch-button.min.js"></script>
    
    <script>
      $(document).ready(function(){
        $(".owl-carousel").owlCarousel({
          items:1,
          loop:true,
          margin:10,
          autoplay:true,
          autoplayTimeout:2000,
          autoplayHoverPause:true
        });
      });

      
    </script>

  </body>
</html>

bms/templates/login.html
{% extends "layout.html" %}
{% block content %}
  <div class="row border mx-auto mt-4 mb-4 auth-form">
    <form action="" method="POST" class="p-3 mt-2 w-100">
      {{ forms.hidden_tag() }}
      <fieldset>
        <legend class="border-bottom title-font pb-3">
         LOGIN!
        </legend>
        <div class="form-group">
          {{ forms.email.label(class="form-control-label") }}
          {% if forms.email.errors %}
          {{ forms.email(class="form-control form-control-lg is-invalid")}}
          <div class="invalid-feedback">
            {% for error in forms.email.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
          {{ forms.email(class="form-control form-control-lg")}}
          {% endif %}
        </div>
        <div class="form-group">
          {{ forms.password.label(class="form-control-label") }}
          {% if forms.password.errors %}
          {{ forms.password(class="form-control form-control-lg is-invalid")}}
          <div class="invalid-feedback">
            {% for error in forms.password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
          {{ forms.password(class="form-control form-control-lg")}}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ forms.submit(class="btn btn-dark") }}
      </div>
    </form>  
    <div class="span ml-auto border-top p-2 text-right" style="width:100%">
      <small class="text-muted p-2">
        Don't have an account? <a href="{{ url_for('main.register') }}">Register</a>
      </small>
    </div>     
  </div>
  
  
{% endblock content %}

bms/templates/parent_dash.html
{% extends 'dashboard_layout.html' %}
{% block content %}
  <div class="">
    <h2>
      Parent_dash
    </h2>
  </div>
{% endblock content%}